[package]
name = "discrim-codegen"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.18"
syn = { version = "1.0.95", features = ["derive", "extra-traits", "parsing"] }

[dev-dependencies]
discrim = { path = "../discrim" }
