name: checks
on: [pull_request, workflow_dispatch]
defaults:
    run:
        shell: bash
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Install Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  components: clippy

            - name: Install just
              run: cargo install just

            - name: Run clippy
              run: just check
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@v2

            - name: Install Rust toolchain
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable

            - name: Run tests
              run: cargo test
